##################################
#         Global settings        #
##################################
server_names = ['dnscrypt.ca-1', 'dnscrypt.ca.2', 'cs-montreal']
listen_addresses = ['127.0.0.1:53']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = false
require_dnssec = false
require_nolog = true
require_nofilter = true
disabled_server_names = []
force_tcp = false
timeout = 1500
keepalive = 30
lb_strategy = 'p2'
lb_estimator = true
ignore_system_dns = true

#########################
#        Filters        #
#########################
block_ipv6 = true
block_unqualified = true
block_undelegated = true
reject_ttl = 3600

###########################
#        DNS cache        #
###########################
cache = true
cache_size = 40960
cache_min_ttl = 3600
cache_max_ttl = 86400
cache_neg_min_ttl = 600
cache_neg_max_ttl = 3600

################################
#        Anonymized DNS        #
################################
[anonymized_dns]
routes = [
        { server_name='dnscrypt.ca-1', via=['anon-zackptg5-us-il-ipv4'] },
        { server_name='dnscrypt.ca-2', via=['anon-plan9-ns1'] }
]
skip_incompatible = true
